name: Performance test AutoFE

on:
  pull_request:
    branches:
    - RecDP_v2.0

jobs:
  unittest:
    name: Performance test AutoFE
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build Docker
      run: |
        cd RecDP && cd Dockerfile && docker build -t pyrecdp-test-env . -f DockerfileUbuntu --build-arg https_proxy=${https_proxy} && cd .. && yes | docker container prune && yes | docker image prune 

    - name : Test ASR
      run: |
        cd RecDP && docker run --rm --name unittest-pyrecdp-autofe-performance-test --shm-size=100g --privileged --network host --device=/dev/dri -v `pwd`:/home/vmagent/app/ -w /home/vmagent/app/ pyrecdp-test-env /bin/bash -c "sh tests/cicd/bashrun_performance_test_autofe.sh"